# Generated by Django 2.2.6 on 2019-11-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=20, null=True)),
                ('twitch_key', models.TextField(blank=True, max_length=35, null=True)),
                ('cobra_key', models.TextField(max_length=32)),
            ],
        ),
    ]
