# Generated by Django 2.2.6 on 2019-11-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='twitch_key',
            new_name='bot_key',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='name',
            new_name='bot_name',
        ),
        migrations.AddField(
            model_name='streamer',
            name='streamer_key',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='streamer_name',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
