# Generated by Django 2.2.6 on 2019-12-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0003_commands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commands',
            new_name='Command',
        ),
    ]
