# Generated by Django 2.2.6 on 2019-12-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0006_auto_20191220_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='cmd',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
